config/routes.rb
Rails.application.routes.draw do
  get 'calculos/calcambul'
  get 'calculos/calcemerg'
  get 'calculos/calcintern'
  resources :pesquisas
  get 'pesquisas/index'
  root to: "pesquisas#index"

  get 'welcome/index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pesquisa.rb
class Pesquisa < ApplicationRecord
    validates :ambulatorio_total, presence:true
    validates :ambul_sat, presence:true
    validates :emergencia_total, presence:true
    validates :emerg_sat, presence:true
    validates :internacao_total, presence:true
    validates :intern_sat, presence:true
    validates :mes, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pesquisas_controller.rb
class PesquisasController < ApplicationController
  before_action :set_pesquisa, only: %i[ show edit update destroy ]

  # GET /pesquisas or /pesquisas.json
  def index
    @pesquisas = Pesquisa.all
  end

  # GET /pesquisas/1 or /pesquisas/1.json
  def show
    @calc_ambulatorio = (@pesquisa.ambulatorio_total * @pesquisa.ambul_sat / 100).to_i
    @calc_emergencia = (@pesquisa.emergencia_total * @pesquisa.emerg_sat / 100).to_i
    @calc_internacao = (@pesquisa.internacao_total * @pesquisa.intern_sat / 100).to_i
    @calc_satifeitos = @calc_ambulatorio + @calc_emergencia + @calc_internacao
    @calc_total = @pesquisa.ambulatorio_total + @pesquisa.emergencia_total + @pesquisa.internacao_total
    @calc_percent_total = (@calc_satifeitos * 100)/@calc_total
  end

  # GET /pesquisas/new
  def new
    @pesquisa = Pesquisa.new
  end

  # GET /pesquisas/1/edit
  def edit
  end

  # POST /pesquisas or /pesquisas.json
  def create
    @pesquisa = Pesquisa.new(pesquisa_params)

    respond_to do |format|
      if @pesquisa.save
        format.html { redirect_to pesquisa_url(@pesquisa), notice: "Pesquisa criada com sucesso." }
        format.json { render :show, status: :created, location: @pesquisa }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pesquisa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pesquisas/1 or /pesquisas/1.json
  def update
    respond_to do |format|
      if @pesquisa.update(pesquisa_params)
        format.html { redirect_to pesquisa_url(@pesquisa), notice: "Pesquisa atualizada com sucesso." }
        format.json { render :show, status: :ok, location: @pesquisa }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pesquisa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pesquisas/1 or /pesquisas/1.json
  def destroy
    @pesquisa.destroy

    respond_to do |format|
      format.html { redirect_to pesquisas_url, notice: "Pesquisa apagada com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pesquisa
      @pesquisa = Pesquisa.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pesquisa_params
      params.require(:pesquisa).permit(:mes, :ambulatorio_total, :ambul_sat, :emergencia_total, :emerg_sat, :internacao_total, :intern_sat)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
    def calc
        @calc_ambulatorio = (@pesquisa.ambulatorio_total * @pesquisa.ambul_sat / 100).to_i
        @calc_emergencia = (@pesquisa.emergencia_total * @pesquisa.emerg_sat / 100).to_i
        @calc_internacao = (@pesquisa.internacao_total * @pesquisa.intern_sat / 100).to_i
        @calc_satifeitos = @calc_ambulatorio + @calc_emergencia + @calc_internacao
        @calc_total = @pesquisa.ambulatorio_total + @pesquisa.emergencia_total + @pesquisa.internacao_total
        @calc_percent_total = (@calc_satifeitos * 100)/@calc_total
    end
end

app/helpers/pesquisas_helper.rb
module PesquisasHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_menu_topo.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-blue">
  <div class="container">
    
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", pesquisas_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Ouvidoria</a>
        </li>
      </ul>
    </div>
    
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ouvidoria</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render :partial => '/layouts/menu_topo' %>
    <%= yield %>
  </body>
</html>

app/views/pesquisas/_form.html.erb
<div class="container">
  <%= form_with(model: pesquisa) do |form| %>
    <div class="row g-6 justify-content-center">
      <% if pesquisa.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(pesquisa.errors.count, "erro") %> proibiu esta pesquisa de ser salva:</h2>

          <ul>
            <% pesquisa.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="row col-8 justify-content-center mb-4">
        <div class="strong col-4 justify-content-center me-5">
          <h4><strong><%= form.label :mes, "Mês vigente:" %></strong></h4>
          <%= form.text_field :mes %>
        </div>
      </div>

      <div class="row col-8 justify-content-center mb-4">
        <h4 class="text-center">Ambulatório</h4>
        <div class="col-4 justify-content-center ms-5">
          <%= form.label :ambulatorio_total, "Total:" %>
          <%= form.text_field :ambulatorio_total %>
        </div>

        <div class="col-4 justify-content-center ms-5">
          <%= form.label :ambul_sat, "Satisfeitos:" %>
          <%= form.text_field :ambul_sat %>%
        </div>
      </div>

      <div class="row col-8 justify-content-center mb-4">
        <h4 class="text-center">Emergência</h4>
        <div class="col-4 justify-content-center ms-5">
          <%= form.label :emergencia_total, "Total:" %>
          <%= form.text_field :emergencia_total %>
        </div>

        <div class="col-4 justify-content-center ms-5">
          <%= form.label :emerg_sat, "Satisfeitos:" %>
          <%= form.text_field :emerg_sat %>%
        </div>
      </div>

      <div class="row col-8 justify-content-center mb-4">
        <h4 class="text-center">Internação</h4>
        <div class="col-4 justify-content-center ms-5">
          <%= form.label :internacao_total, "Total:" %>
          <%= form.text_field :internacao_total %>
        </div>

        <div class="col-4 justify-content-center ms-5">
          <%= form.label :intern_sat, "Satisfeitos:" %>
          <%= form.text_field :intern_sat %>%
        </div>
      </div>

      <div class="row col-8 d-grid gap-2 justify-content-md-end">
        <%= form.submit "Salvar", class: "btn btn-success" %>
      </div>
    </div>
  <% end %>
</div?

app/views/pesquisas/edit.html.erb
<div class="container">

<div class="row align-items-center mb-3">
    <div class="col-3">
        <%= image_tag "logos/logo_azul_hegv.png", :class => "w-50 p-3 d-block mx-auto mb-4" %>
    </div>
    <div class="col-6">
    <h1>Editar mês de <%= @pesquisa.mes %></h1>
    </div>
    <div class="col-3">
        <%= image_tag "logos/pe_secretaria.png", :class => "w-50 p-3 d-block mx-auto mb-4" %>
    </div>
</div>

    <%= render 'form', pesquisa: @pesquisa %>
    <div class= "row col-8 justify-content-start">
        <%= link_to 'Mostrar', @pesquisa, class: "btn btn-primary" %>
        <%= link_to 'Voltar', pesquisas_path, class: "btn btn-primary" %>
    </div>
</div>

app/views/pesquisas/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <div class="row align-items-center mb-5">
    <div class="col-3">
    <%= image_tag "logos/logo_azul_hegv.png", :class => "w-75 p-3 d-block mx-auto mb-4" %>
    
    </div>
    <div class="col-6">
      <h1>Pesquisas de Satisfação</h1>
    </div>
    <div class="col-3">
    <%= image_tag "logos/pe_secretaria.png", :class => "w-75 p-3 d-block mx-auto mb-4" %>
    </div>
    
    <h2></h2>
    <p class="lead">Dados extraídos do site Ouvidoria da Secretaria de Saúde</p>
  </div>
  
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Mês vigente</th>
        <th scope="col">Ambulatório total</th>
        <th scope="col">Ambulatório satisfeitos</th>
        <th scope="col">Emergência total</th>
        <th scope="col">Emergência satisfeitos</th>
        <th scope="col">Internação total</th>
        <th scope="col">Internação satisfeitos</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @pesquisas.each do |pesquisa| %>
        <tr>
          <td><%= pesquisa.mes %></td>
          <td><%= pesquisa.ambulatorio_total %></td>
          <td><%= pesquisa.ambul_sat %></td>
          <td><%= pesquisa.emergencia_total %></td>
          <td><%= pesquisa.emerg_sat %></td>
          <td><%= pesquisa.internacao_total %></td>
          <td><%= pesquisa.intern_sat %></td>
          <td><%= link_to 'Mostrar', pesquisa, class: "btn btn-success" %></td>
          <td><%= link_to 'Editar', edit_pesquisa_path(pesquisa), class: "btn btn-warning" %></td>
          <td><%= link_to 'Apagar', pesquisa, method: :delete, data: { confirm: 'Você tem certeza?' }, class: "btn btn-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Nova Pesquisa', new_pesquisa_path, class: "btn btn-success" %>
  </div>

app/views/pesquisas/new.html.erb
<div class="container">
    <div class="row justify-content-center mt-4 mb-4">
        <h1 class="row justify-content-center text-blue">Nova Pesquisa</h1>
    </div>
    
    <%= render 'form', pesquisa: @pesquisa %>
    
    <div class= "row col-8 justify-content-start"><%= link_to 'Back', pesquisas_path, class: "btn btn-primary" %></div>
    
</div>

app/views/pesquisas/show.html.erb
<div class="container">

  <p id="notice"><%= notice %></p>


    <div class="row align-items-center mb-5">
      <div class="col-3">
      <%= image_tag "logos/logo_azul_hegv.png", :class => "w-75 p-3 d-block mx-auto mb-4" %>
      
      </div>
      <div class="col-6">
        <h2>Pesquisa do mês de <%= @pesquisa.mes %></h2>
      </div>
      <div class="col-3">
      <%= image_tag "logos/pe_secretaria.png", :class => "w-75 p-3 d-block mx-auto mb-4" %>
      </div>
      
      <h2></h2>
      <p class="lead">Dados extraídos do site Ouvidoria da Secretaria de Saúde</p>
        
    </div>
    
    <table class="table table-bordered table-striped">
    <h5><strong>Data de criação:</strong> <%= @pesquisa.created_at.strftime("%d/%m/%Y") %></h5>
    <h5 class="mb-5"><strong>Data de atualização:</strong> <%= @pesquisa.updated_at.strftime("%d/%m/%Y") %></h5>
      <thead class="table-primary">
        <tr>
          <th colspan="3">Ambulatório</th>
          <th colspan="3">Emergência</th>
          <th colspan="3">Internação</th>
        </tr>
      </thead>
      <thead>
        <tr>
          <th scope="col">Pesquisados</th>
          <th scope="col">Total</th>
          <th scope="col">Satisfeitos</th>
          <th scope="col">Pesquisados</th>
          <th scope="col">Total</th>
          <th scope="col">Satisfeitos</th>
          <th scope="col">Pesquisados</th>
          <th scope="col">Total</th>
          <th scope="col">Satisfeitos</th>
        </tr>
      </thead>
      
      <tbody>
          <tr>
            <td><%= @pesquisa.ambulatorio_total %></td>
            <td><%= @calc_ambulatorio %></td>
            <td><%= @pesquisa.ambul_sat %>%</td>
            <td><%= @pesquisa.emergencia_total %></td>
            <td><%= @calc_emergencia %></td>
            <td><%= @pesquisa.emerg_sat %>%</td>
            <td><%= @pesquisa.internacao_total %></td>
            <td><%= @calc_internacao %></td>
            <td><%= @pesquisa.intern_sat %>%</td>
          </tr>
      </tbody>
    </table>

    <table class="table table-bordered table-striped">
    
      <thead class="table-primary">
        <tr>
          <th scope="col">Total de Respostas</th>
          <th scope="col">Respostas Positivas</th>
          <th scope="col">Percentual</th>
        </tr>
      </thead>
      
      <tbody>
          <tr>
            <td><%= @calc_total %></td>
            <td><%= @calc_satifeitos %></td>
            <td><%= @calc_percent_total %>%</td>
          </tr>
      </tbody>
    </table>
   
    
</div>

app/views/welcome/index.html.erb
<div class="collapse" id="navbarToggleExternalContent">
  <div class="bg-dark p-4">
    <h5 class="text-white h4">Collapsed content</h5>
    <span class="text-muted">Toggleable via the navbar brand.</span>
  </div>
</div>
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</nav>

<main>
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Album example</h1>
        <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
        <p>
          <a href="#" class="btn btn-primary my-2">Main call to action</a>
          <a href="#" class="btn btn-secondary my-2">Secondary action</a>
        </p>
      </div>
    </div>
  </section>
</main>